### ISSUE TITLE
this works with AMD? 

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [lks-ai/ComfyUI-StableAudioSampler#2]

**Comment by ArkhamInsanity** [comment]
Currently using it on my ubuntu pc with AMD 6800XT graphic card, about 45 seconds for 45 seconds songs with defaults parameters (100 steps)

**Comment by KillyTheNetTerminal** [comment]
oh, cool, but using rocm? I use directml on windows (Rx580) how did you install this? i get errors and my comfy installation corrupted

**Comment by ArkhamInsanity** [comment]
> oh, cool, but using rocm? I use directml on windows (Rx580) how did you install this? i get errors and my comfy installation corrupted

Yes with rocm, never tried to use directml on windows myself, sorry.

**Comment by badbod** [comment]
hmm, requires flash_attn which quires nvidia no?   How did you get it working on AMD?

```
TypeError: expected string or bytes-like object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash_attn
  Running setup.py clean for flash_attn
Failed to build flash_attn

```

**Comment by ArkhamInsanity** [comment]
> hmm, requires flash_attn which requires nvidia no? How did you get it working with rocm?
> 
> ```
> TypeError: expected string or bytes-like object
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for flash_attn
>   Running setup.py clean for flash_attn
> Failed to build flash_attn
> ```

I don't know how to help you, I used comfyui manager to install like everything I install in comfyui and it worked right away

**Comment by badbod** [comment]
I think it is since StableAudioSampler was updated today/yesterday? I installed it fine from the comfy manager last week. But today, no go. Anyway, I found there is a ROCm flash_attn from our friends @ AMD.com

https://rocm.docs.amd.com/en/latest/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.html

This installs Flash Attention 2 ROCm and the node is available. In process of testing if it actually works but I'm confident.
:-)

**Comment by KillyTheNetTerminal** [comment]
I'm a little confused about all this haha... flash attention is something that is not available in Directml? Rocm, what is it about? I installed a comfy Zluda version and it also disables that option

**Comment by ArkhamInsanity** [comment]
> I think it is since StableAudioSampler was updated today/yesterday? I installed it fine from the comfy manager last week. But today, no go. Anyway, I found there is a ROCm flash_attn from our friends @ AMD.com
> 
> https://rocm.docs.amd.com/en/latest/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.html
> 
> This installs Flash Attention 2 ROCm and the node is available. In process of testing if it actually works but I'm confident. :-)

I have to update^^ Tomorrow I may have more time to try it



> I'm a little confused about all this haha... flash attention is something that is not available in Directml? Rocm, what is it about? I installed a comfy Zluda version and it also disables that option

I am not really good with the tech, but Rocm works on linux and soon on windows.

**Comment by badbod** [comment]
Well I tried,
 option one installed but told me it only works on MI 200/300 GPU's  (it tells me that when I try to run a workflow) ,
 the other option 'Triton' wont build, it fails getting the pytorch version. 

No issues with ROCm, pytorch and onnxruntime work fine using ROCm 6.0.2 (stable) 

As flash_attn errors out of building the wheel at the pytorch version check I am assuming it wants an older ROCm like 5.7 maybe? as this changes the version number of pytorch (adds rocm-6.0 to the version number)

Arch Linux
Pythons 3.10 through 3.12 tested
Pytorch ROCm 6.0.2  from official site (https://pytorch.org/get-started/locally/)

Clean venv and just install pytorch then try to install flash_attn

**Comment by badbod** [comment]
> I'm a little confused about all this haha... flash attention is something that is not available in Directml? Rocm, what is it about? I installed a comfy Zluda version and it also disables that option.

seems on linux one of the dependencies for one of the requirements for StableAudioSampler is flash_attn, I have never come accross it before but there it is. Don't know what changed as I did install StableAudioSampler only a week ago without issues somwhere in between this flash_attn appeared as a dependency.


windows uses DirectML/Zluda  On Linux, for AMD, we use ROCm/OpenCL.

**Comment by badbod** [comment]
> I'm a little confused about all this haha... flash attention is something that is not available in Directml? Rocm, what is it about? I installed a comfy Zluda version and it also disables that option

oops, sorry, then Iv hijacked your thread, just assumed linux, ,   err yes, As far as I am aware this works for AMD , just not today on linux  LOL

**Comment by badbod** [comment]
err, hmm, ok,   well,  remove the **flash_attn** line from your requirements.txt,  then do 
pip install -r requirements.txt everything goes fine and dandy without flash_attn,  comfyui workflow working fine and outputting music. Solved, pheeewww,  tested on python 3.10

**Comment by ArkhamInsanity** [comment]
You should definitely post your own issue topic if you want the developper to take care of it

**Comment by ghost** [comment]
No:
```
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      /tmp/pip-install-2csih0px/flash-attn_66cd5b178693478e981a01389ec47d60/setup.py:106: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2csih0px/flash-attn_66cd5b178693478e981a01389ec47d60/setup.py", line 230, in <module>
          CUDAExtension(
        File "/mnt/old_drive/code/comfy-env-310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1279, in CUDAExtension
          library_dirs += library_paths(device_type="cuda")
        File "/mnt/old_drive/code/comfy-env-310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1490, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/mnt/old_drive/code/comfy-env-310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2889, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.7.1+rocm6.3
      
      
      [end of output]
```
