### ISSUE TITLE
(IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler

### ISSUE THREAD

**Issue by Xenodimensional** [lks-ai/ComfyUI-StableAudioSampler#20]
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\__init__.py", line 8, in <module>
    from .nodes import StableAudioSampler, NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\nodes.py", line 6, in <module>
    from stable_audio_tools import get_pretrained_model
ModuleNotFoundError: No module named 'stable_audio_tools'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler module for custom nodes: No module named 'stable_audio_tools'
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...

**Comment by 3blackbar** [comment]
same issue here !

**Comment by 3blackbar** [comment]
Can You boot it and not use  progressbar at all? The least amount of dependencies the better for users

**Comment by 3blackbar** [comment]
This shiz aint working, gives no solution, so id say do not use progressbar if it also breaks other nodes      


If you get the progressbar error, you can use our new utility from the latest update.

cd ComfyUI/custom_modules/ComfyUI-StableAudioSampler
python util_discrepancies.py progressbar
You will see something like this... Screenshot from 2024-06-13 13-02-30 In this screenshot, you see protobuf but that is only because I don't have version issues with progressbar. Note: If I install one of those version suggestions, StableAudioSampler should work, but at the same time, it might make other packages not work.

**Comment by Yinghoo** [comment]
Similar Issue, 

I remove the "Stability-AI/stable audio tools" file into "ComfyUI- Stable Audio Sampler" file ,the issue show"  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed"

Is it mean I miss this module”importlib._bootstrap“, how could I deal solve this issue?  should I reinstall stable Audio tools?
Here is my log .text:"
Traceback (most recent call last):
  File "C:\Users\86132\projects\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\86132\projects\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\__init__.py", line 8, in <module>
    from .nodes import StableAudioSampler, NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\86132\projects\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\nodes.py", line 11, in <module>
    from stable_audio_tools import get_pretrained_model
ModuleNotFoundError: No module named 'stable_audio_tools'

Cannot import C:\Users\86132\projects\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler module for custom nodes: No module named 'stable_audio_tools'

**Comment by GomuSkelly** [comment]
@Xenodimensional @Yinghoo The information provided by @marius-jopen here: https://github.com/lks-ai/ComfyUI-StableAudioSampler/issues/30 might help you get this node running.
