### ISSUE TITLE
ModuleNotFoundError: No module named 'stable_audio_tools'

### ISSUE THREAD

**Issue by Atteronious** [lks-ai/ComfyUI-StableAudioSampler#21]
After installing the module via ComfyUI Manager and restarting Comfy I get the following message in the cmd window:

Traceback (most recent call last):
  File "E:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\__init__.py", line 8, in <module>
    from .nodes import StableAudioSampler, NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\nodes.py", line 6, in <module>
    from stable_audio_tools import get_pretrained_model
ModuleNotFoundError: No module named 'stable_audio_tools'

Cannot import E:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler module for custom nodes: No module named 'stable_audio_tools'

**Comment by Cal-DCosta** [comment]
I get the same and it goes into a loop trying to find 'stable_audio_tools' so much so that I deleted the custom_nodes - stable audio folder so that comfy starts up.

**Comment by tgitit** [comment]
I am also getting a similar error to the op. 

However if posting the error code, when I preview it some information is ommited.

See below, with <> removed after and before "". For some reason if <> are present, the code is stripped out

"frozen importlib._bootstrap_external", line 940, in exec_module
"frozen importlib._bootstrap", line 241, in _call_with_frames_removed

**Comment by azulika** [comment]
same

**Comment by birkb85** [comment]
same

**Comment by GomuSkelly** [comment]
The information provided by @marius-jopen here: https://github.com/lks-ai/ComfyUI-StableAudioSampler/issues/30 might help you get this node running.
