### ISSUE TITLE
util_discrepancies.py  ?

### ISSUE THREAD

**Issue by EricRollei** [lks-ai/ComfyUI-StableAudioSampler#22]
Thank you for making the nodes.
Have been unable to install the stable audio tools and have seen the progressbar error.   Trying to follow the instructions on the readme but can't find the util_discrepancies.py file.  I've got  ComfyUI/custom_nodes/ComfyUI-StableAudioSampler  but not anything with \custom_modules\ and don't see the util file either.

**Comment by EricRollei** [comment]
I'm sure you meant util_dependencies.py
But when I run that I get no suggestions to try

A:\Comfy_Dec\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler>python util_dependencies.py progressbar
A:\Comfy_Dec\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler\util_dependencies.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Dependents of 'progressbar':

Analyzing package discrepancies...

Suggested solutions:
Analyzing package discrepancies...
 
And I still have the error no progressbar found:

A:\Comfy_Dec\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler>A:\Comfy_Dec\python_embeded\python.exe -m pip install -r requirements.txt
Collecting stable-audio-tools (from -r requirements.txt (line 1))
  Using cached stable_audio_tools-0.0.16-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: torch in a:\comfy_dec\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (2.3.1+cu121)
Requirement already satisfied: torchaudio in a:\comfy_dec\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.3.1+cu121)
Requirement already satisfied: einops in a:\comfy_dec\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: numpy in a:\comfy_dec\python_embeded\lib\site-packages (from -r requirements.txt (line 5)) (1.26.4)
Requirement already satisfied: aeiou in a:\comfy_dec\python_embeded\lib\site-packages (from -r requirements.txt (line 6)) (0.0.20)
Collecting flash_attn (from -r requirements.txt (line 7))
  Using cached flash_attn-2.5.9.post1.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... done
Collecting alias-free-torch==0.0.6 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached alias_free_torch-0.0.6-py3-none-any.whl.metadata (3.8 kB)
Collecting auraloss==0.4.0 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached auraloss-0.4.0-py3-none-any.whl.metadata (8.0 kB)
Collecting descript-audio-codec==1.0.0 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached descript_audio_codec-1.0.0-py3-none-any.whl.metadata (7.8 kB)
Collecting einops (from -r requirements.txt (line 4))
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting einops-exts==0.0.4 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached einops_exts-0.0.4-py3-none-any.whl.metadata (621 bytes)
Collecting ema-pytorch==0.2.3 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached ema_pytorch-0.2.3-py3-none-any.whl.metadata (693 bytes)
Requirement already satisfied: encodec==0.1.1 in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (0.1.1)
Requirement already satisfied: gradio>=3.42.0 in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (4.21.0)
Requirement already satisfied: huggingface-hub in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (0.23.2)
Collecting importlib-resources==5.12.0 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached importlib_resources-5.12.0-py3-none-any.whl.metadata (4.1 kB)
Collecting k-diffusion==0.1.1 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached k_diffusion-0.1.1-py3-none-any.whl.metadata (3.9 kB)
Collecting laion-clap==1.1.4 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached laion_clap-1.1.4-py3-none-any.whl.metadata (26 kB)
Collecting local-attention==1.8.6 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached local_attention-1.8.6-py3-none-any.whl.metadata (684 bytes)
Collecting pandas==2.0.2 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached pandas-2.0.2-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting pedalboard==0.7.4 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached pedalboard-0.7.4-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting prefigure==0.0.9 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached prefigure-0.0.9-py3-none-any.whl.metadata (5.9 kB)
Collecting pytorch-lightning==2.1.0 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached pytorch_lightning-2.1.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: PyWavelets==1.4.1 in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: safetensors in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: sentencepiece==0.1.99 in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (0.1.99)
Collecting s3fs (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached s3fs-2024.6.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: torchmetrics==0.11.4 in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (0.11.4)
Requirement already satisfied: tqdm in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (4.66.4)
Requirement already satisfied: transformers in a:\comfy_dec\python_embeded\lib\site-packages (from stable-audio-tools->-r requirements.txt (line 1)) (4.38.2)
Collecting v-diffusion-pytorch==0.0.2 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached v_diffusion_pytorch-0.0.2-py3-none-any.whl.metadata (10.0 kB)
Collecting vector-quantize-pytorch==1.9.14 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached vector_quantize_pytorch-1.9.14-py3-none-any.whl.metadata (681 bytes)
Collecting wandb==0.15.4 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached wandb-0.15.4-py3-none-any.whl.metadata (8.1 kB)
Collecting webdataset==0.2.48 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached webdataset-0.2.48-py3-none-any.whl.metadata (29 kB)
Collecting x-transformers<1.27.0 (from stable-audio-tools->-r requirements.txt (line 1))
  Using cached x_transformers-1.26.6-py3-none-any.whl.metadata (661 bytes)
Requirement already satisfied: fastcore in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (1.5.29)
Requirement already satisfied: plotly in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (5.22.0)
Requirement already satisfied: bokeh in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (3.4.1)
Requirement already satisfied: holoviews in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (1.19.0)
Requirement already satisfied: scipy in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (1.13.1)
Requirement already satisfied: torchvision in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (0.18.1+cu121)
Requirement already satisfied: matplotlib in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (3.8.1)
Requirement already satisfied: pillow in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (10.3.0)
Requirement already satisfied: librosa>=0.8.1 in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (0.9.2)
Requirement already satisfied: ipython in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (8.22.2)
Requirement already satisfied: accelerate in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (0.27.2)
Requirement already satisfied: soundfile<=0.10.2 in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (0.10.2)
Requirement already satisfied: umap-learn in a:\comfy_dec\python_embeded\lib\site-packages (from aeiou->-r requirements.txt (line 6)) (0.5.6)
Collecting argbind>=0.3.7 (from descript-audio-codec==1.0.0->stable-audio-tools->-r requirements.txt (line 1))
  Using cached argbind-0.3.9.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting descript-audiotools>=0.7.2 (from descript-audio-codec==1.0.0->stable-audio-tools->-r requirements.txt (line 1))
  Using cached descript_audiotools-0.7.2-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting clean-fid (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1))
  Using cached clean_fid-0.1.35-py3-none-any.whl.metadata (36 kB)
Collecting clip-anytorch (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1))
  Using cached clip_anytorch-2.6.0-py3-none-any.whl.metadata (8.4 kB)
Collecting dctorch (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1))
  Using cached dctorch-0.1.2-py3-none-any.whl.metadata (607 bytes)
Collecting jsonmerge (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1))
  Using cached jsonmerge-1.9.2-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: kornia in a:\comfy_dec\python_embeded\lib\site-packages (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1)) (0.7.2)
Requirement already satisfied: scikit-image in a:\comfy_dec\python_embeded\lib\site-packages (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1)) (0.20.0)
Requirement already satisfied: torchdiffeq in a:\comfy_dec\python_embeded\lib\site-packages (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1)) (0.2.3)
Requirement already satisfied: torchsde in a:\comfy_dec\python_embeded\lib\site-packages (from k-diffusion==0.1.1->stable-audio-tools->-r requirements.txt (line 1)) (0.2.6)
Collecting numpy (from -r requirements.txt (line 5))
  Using cached numpy-1.23.5-cp311-cp311-win_amd64.whl.metadata (2.3 kB)
Collecting torchlibrosa (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1))
  Using cached torchlibrosa-0.1.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: ftfy in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (6.1.1)
Requirement already satisfied: braceexpand in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (0.1.7)
Requirement already satisfied: wget in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (3.2)
Requirement already satisfied: llvmlite in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (0.41.1)
Requirement already satisfied: scikit-learn in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (1.3.2)
Collecting h5py (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1))
  Using cached h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Requirement already satisfied: regex in a:\comfy_dec\python_embeded\lib\site-packages (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1)) (2023.10.3)
Collecting progressbar (from laion-clap==1.1.4->stable-audio-tools->-r requirements.txt (line 1))
  Using cached progressbar-2.5.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Eric Hiss\AppData\Local\Temp\pip-install-dgsodplr\progressbar_7770a7eb22f04d778d43decfb580ca53\setup.py", line 5, in <module>
          import progressbar
      **ModuleNotFoundError: No module named 'progressbar'**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

A:\Comfy_Dec\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler>

**Comment by birkb85** [comment]
I have the same problem..

**Comment by birkb85** [comment]
For anyone interrested comfyui now got official support for StabilityAI Open Audio.
https://comfyanonymous.github.io/ComfyUI_examples/audio/?ref=blog.comfy.org

**Comment by GomuSkelly** [comment]
@EricRollei The information provided by @marius-jopen here: https://github.com/lks-ai/ComfyUI-StableAudioSampler/issues/30 might help you get this node running.
