### ISSUE TITLE
StableAudio Broken

### ISSUE THREAD

**Issue by sirolim** [lks-ai/ComfyUI-StableAudioSampler#23]
StableAudio is broken for me. Can't make it work with a fresh install yet.
Get this error when trying to fix it through the manager. Don't know what to do. Tried deleting venv, torch, pytorch, reinstall everything. I'm not a programmer so a bit clueless. Would be really thankful if anybody can help here 

...

Collecting progressbar (from laion-clap==1.1.4->stable-audio-tools)
   Using cached progressbar-2.5.tar.gz (10 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\peter\AppData\Local\Temp\pip-install-09on08te\progressbar_73830bee1f5940aa81158a33483886f1\setup.py", line 5, in <module>
[!]       import progressbar
[!]   ModuleNotFoundError: No module named 'progressbar'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler

## Execute install/(de)activation script for 'C:\Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler'
 Collecting flash_attn
   Using cached flash_attn-2.5.9.post1.tar.gz (2.6 MB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'
              Building wheels for collected packages: flash_attn
   Building wheel for flash_attn (setup.py): started

**Comment by birkb85** [comment]
same

**Comment by 3blackbar** [comment]
its the damn progressbar

**Comment by birkb85** [comment]
For anyone interrested comfyui now got official support for StabilityAI Open Audio.
https://comfyanonymous.github.io/ComfyUI_examples/audio/?ref=blog.comfy.org

**Comment by GomuSkelly** [comment]
@birkb85 This node does more than the core implementation from what I gather. 

@sirolim The information provided by @marius-jopen here: https://github.com/lks-ai/ComfyUI-StableAudioSampler/issues/30 might help you get this node running.
