### ISSUE TITLE
(IMPORT FAILED) ComfyUI Stable Audio Open 1.0 Sampler

### ISSUE THREAD

**Issue by AlgorithmicKing** [lks-ai/ComfyUI-StableAudioSampler#24]
![Screenshot 2024-06-20 121020](https://github.com/lks-ai/ComfyUI-StableAudioSampler/assets/147901320/1ac8d3d1-5a56-43e9-8367-e9d393c1c677)

**Comment by birkb85** [comment]
I have the same issue...
I think maybe (for me) it has something to do with the "Error: progressbar" as mentioned in the readme, but there is no file named util_discrepancies.py which should supposedly fix it?

**Comment by AlgorithmicKing** [comment]
hopefully a contributor comments on this issue

**Comment by mr360photo** [comment]
Same here ~ tried on a fresh portable ComFy install, no joy...

**Comment by Norby123** [comment]
Yep, same here:

```
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-e1tuwkvv\progressbar_2844d80de36a476ea8b1bd1b3fa6116e\setup.py", line 5, in <module>
[!]       import progressbar
[!]   ModuleNotFoundError: No module named 'progressbar'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler
```



```
## ComfyUI-Manager: EXECUTE => ['C:\\Sajat\\StableDiffusion\\APP\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'flash_attn']

## Execute install/(de)activation script for 'C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler'
 Collecting flash_attn
   Downloading flash_attn-2.5.9.post1.tar.gz (2.6 MB)
      ---------------------------------------- 2.6/2.6 MB 20.8 MB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [22 lines of output]
[!]   fatal: not a git repository (or any of the parent directories): .git
[!]   C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
[!]     warnings.warn(
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py", line 134, in <module>
[!]       CUDAExtension(
[!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1077, in CUDAExtension
[!]       library_dirs += library_paths(cuda=True)
[!]                       ^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1211, in library_paths
[!]       paths.append(_join_cuda_home(lib_dir))
[!]                    ^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2419, in _join_cuda_home
[!]       raise OSError('CUDA_HOME environment variable is not set. '
[!]   OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
[!]
[!]
[!]   torch.__version__  = 2.3.1+cu121
[!]
[!]
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler

[ComfyUI-Manager] Startup script completed.
#######################################################################

```

Should we manually download or install something?

**Comment by AlgorithmicKing** [comment]
@lks-ai please reply

**Comment by birkb85** [comment]
> Yep, same here:
> 
> ```
>    Preparing metadata (setup.py): started
>    Preparing metadata (setup.py): finished with status 'error'
> [!]   error: subprocess-exited-with-error
> [!]
> [!]   python setup.py egg_info did not run successfully.
> [!]   exit code: 1
> [!]
> [!]   [6 lines of output]
> [!]   Traceback (most recent call last):
> [!]     File "<string>", line 2, in <module>
> [!]     File "<pip-setuptools-caller>", line 34, in <module>
> [!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-e1tuwkvv\progressbar_2844d80de36a476ea8b1bd1b3fa6116e\setup.py", line 5, in <module>
> [!]       import progressbar
> [!]   ModuleNotFoundError: No module named 'progressbar'
> [!]   [end of output]
> [!]
> [!]   note: This error originates from a subprocess, and is likely not a problem with pip.
> [!] error: metadata-generation-failed
> [!]
> [!] Encountered error while generating package metadata.
> [!]
> [!] See above for output.
> [!]
> [!] note: This is an issue with the package mentioned above, not pip.
> [!] hint: See above for details.
> install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler
> ```
> 
>  ```
> ## ComfyUI-Manager: EXECUTE => ['C:\\Sajat\\StableDiffusion\\APP\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'flash_attn']
> 
> ## Execute install/(de)activation script for 'C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler'
>  Collecting flash_attn
>    Downloading flash_attn-2.5.9.post1.tar.gz (2.6 MB)
>       ---------------------------------------- 2.6/2.6 MB 20.8 MB/s eta 0:00:00
>    Preparing metadata (setup.py): started
>    Preparing metadata (setup.py): finished with status 'error'
> [!]   error: subprocess-exited-with-error
> [!]
> [!]   python setup.py egg_info did not run successfully.
> [!]   exit code: 1
> [!]
> [!]   [22 lines of output]
> [!]   fatal: not a git repository (or any of the parent directories): .git
> [!]   C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
> [!]     warnings.warn(
> [!]   Traceback (most recent call last):
> [!]     File "<string>", line 2, in <module>
> [!]     File "<pip-setuptools-caller>", line 34, in <module>
> [!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py", line 134, in <module>
> [!]       CUDAExtension(
> [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1077, in CUDAExtension
> [!]       library_dirs += library_paths(cuda=True)
> [!]                       ^^^^^^^^^^^^^^^^^^^^^^^^
> [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1211, in library_paths
> [!]       paths.append(_join_cuda_home(lib_dir))
> [!]                    ^^^^^^^^^^^^^^^^^^^^^^^^
> [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2419, in _join_cuda_home
> [!]       raise OSError('CUDA_HOME environment variable is not set. '
> [!]   OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
> [!]
> [!]
> [!]   torch.__version__  = 2.3.1+cu121
> [!]
> [!]
> [!]   [end of output]
> [!]
> [!]   note: This error originates from a subprocess, and is likely not a problem with pip.
> [!] error: metadata-generation-failed
> [!]
> [!] Encountered error while generating package metadata.
> [!]
> [!] See above for output.
> [!]
> [!] note: This is an issue with the package mentioned above, not pip.
> [!] hint: See above for details.
> install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler
> 
> [ComfyUI-Manager] Startup script completed.
> #######################################################################
> ```
> 
> Should we manually download or install something?

I wait for a solution I dont want to possibly break my comfyui installation..

**Comment by AlgorithmicKing** [comment]
> > Yep, same here:
> > ```
> >    Preparing metadata (setup.py): started
> >    Preparing metadata (setup.py): finished with status 'error'
> > [!]   error: subprocess-exited-with-error
> > [!]
> > [!]   python setup.py egg_info did not run successfully.
> > [!]   exit code: 1
> > [!]
> > [!]   [6 lines of output]
> > [!]   Traceback (most recent call last):
> > [!]     File "<string>", line 2, in <module>
> > [!]     File "<pip-setuptools-caller>", line 34, in <module>
> > [!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-e1tuwkvv\progressbar_2844d80de36a476ea8b1bd1b3fa6116e\setup.py", line 5, in <module>
> > [!]       import progressbar
> > [!]   ModuleNotFoundError: No module named 'progressbar'
> > [!]   [end of output]
> > [!]
> > [!]   note: This error originates from a subprocess, and is likely not a problem with pip.
> > [!] error: metadata-generation-failed
> > [!]
> > [!] Encountered error while generating package metadata.
> > [!]
> > [!] See above for output.
> > [!]
> > [!] note: This is an issue with the package mentioned above, not pip.
> > [!] hint: See above for details.
> > install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ## ComfyUI-Manager: EXECUTE => ['C:\\Sajat\\StableDiffusion\\APP\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'flash_attn']
> > 
> > ## Execute install/(de)activation script for 'C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler'
> > Collecting flash_attn
> >   Downloading flash_attn-2.5.9.post1.tar.gz (2.6 MB)
> >      ---------------------------------------- 2.6/2.6 MB 20.8 MB/s eta 0:00:00
> >   Preparing metadata (setup.py): started
> >   Preparing metadata (setup.py): finished with status 'error'
> > [!]   error: subprocess-exited-with-error
> > [!]
> > [!]   python setup.py egg_info did not run successfully.
> > [!]   exit code: 1
> > [!]
> > [!]   [22 lines of output]
> > [!]   fatal: not a git repository (or any of the parent directories): .git
> > [!]   C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
> > [!]     warnings.warn(
> > [!]   Traceback (most recent call last):
> > [!]     File "<string>", line 2, in <module>
> > [!]     File "<pip-setuptools-caller>", line 34, in <module>
> > [!]     File "C:\Users\Norby\AppData\Local\Temp\pip-install-x3x7vdy2\flash-attn_06ae9d2db0b5490aafa8a64adc24afbc\setup.py", line 134, in <module>
> > [!]       CUDAExtension(
> > [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1077, in CUDAExtension
> > [!]       library_dirs += library_paths(cuda=True)
> > [!]                       ^^^^^^^^^^^^^^^^^^^^^^^^
> > [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1211, in library_paths
> > [!]       paths.append(_join_cuda_home(lib_dir))
> > [!]                    ^^^^^^^^^^^^^^^^^^^^^^^^
> > [!]     File "C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2419, in _join_cuda_home
> > [!]       raise OSError('CUDA_HOME environment variable is not set. '
> > [!]   OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
> > [!]
> > [!]
> > [!]   torch.__version__  = 2.3.1+cu121
> > [!]
> > [!]
> > [!]   [end of output]
> > [!]
> > [!]   note: This error originates from a subprocess, and is likely not a problem with pip.
> > [!] error: metadata-generation-failed
> > [!]
> > [!] Encountered error while generating package metadata.
> > [!]
> > [!] See above for output.
> > [!]
> > [!] note: This is an issue with the package mentioned above, not pip.
> > [!] hint: See above for details.
> > install/(de)activation script failed: C:\Sajat\StableDiffusion\APP\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableAudioSampler
> > 
> > [ComfyUI-Manager] Startup script completed.
> > #######################################################################
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should we manually download or install something?
> 
> I wait for a solution I dont want to possibly break my comfyui installation..

I already broke my ComfyUI Installation XD I don't know if it was because of this or another node but it still broke. At least the models didn't get deleted.

**Comment by OneTimePads** [comment]
For me protobuf-4.25.3 worked with both StableAudioSampler and AnyNode 
`pip install protobuf==4.25.3`

**Comment by AlgorithmicKing** [comment]
> For me protobuf-4.25.3 worked with both StableAudioSampler and AnyNode `pip install protobuf==4.25.3`

thanks a lot i'll try that

**Comment by birkb85** [comment]
For anyone interrested comfyui now got official support for StabilityAI Open Audio.
https://comfyanonymous.github.io/ComfyUI_examples/audio/?ref=blog.comfy.org

**Comment by AlgorithmicKing** [comment]
> For anyone interrested comfyui now got official support for StabilityAI Open Audio. https://comfyanonymous.github.io/ComfyUI_examples/audio/?ref=blog.comfy.org

OH REWALLYT?!?!?!? thanks a lot i really needed it

**Comment by PittStone** [comment]
Thats sad. Its not working anymore. I try'd many times, but only Any Node is installed. "StableAudioSampler" doesn't.

**Comment by GomuSkelly** [comment]
The information provided by @marius-jopen on the following issue discussion might help you get this node running: https://github.com/lks-ai/ComfyUI-StableAudioSampler/issues/30

@Norby123 @PittStone @lks-ai @mr360photo @birkb85 @AlgorithmicKing
