### ISSUE TITLE
使用save audio节点报错

### ISSUE THREAD

**Issue by vanche1212** [lks-ai/ComfyUI-StableAudioSampler#25]
2024-06-27 11:39:01,193- root:285- ERROR- Traceback (most recent call last):
  File "/data/ComfyUI/execution.py", line 245, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/ComfyUI/comfy_extras/nodes_audio.py", line 75, in save_audio
    for (batch_number, waveform) in enumerate(audio["waveform"]):
TypeError: byte indices must be integers or slices, not str

**Comment by fangg2000** [comment]
每次更新comfyui都要先删除numpy再安装，好烦，现在最新版本这个方法也没效果了，我在想有什么办法能解决这个问题……

**Comment by lishuai1993** [comment]
不要使用预览或者保存音频节点，使用节点LayerUtility: Purge VRAM，从output中可以看到最新生成的音频文件
